version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - JWT_SECRET=change_this_secret
    volumes:
      - ./backend/data:/app/data
      - ./backend/model:/app/model
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
